accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "CDLA-Permissive-2.0",
    "MPL-2.0",
    "BSL-1.0",
    "CC0-1.0",
    "Unlicense",
]
targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabihf",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
workarounds = ["ring", "rustls"]

[ring]
accepted = ["OpenSSL"]
